// default package
// Generated Jun 17, 2016 6:39:21 PM by Hibernate Tools 4.3.1.Final

/**
 * Properties generated by hbm2java
 */
package it.reply.monitoring.dao;

public class Properties implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer monitId;
	private String wsDebugEnabled;
	private String multipleServersEnabled;
	private String proxyArchitectureEnabled;
	private String iaasMonitoringEnabled;
	private String adapterName;
	private String adapterVersion;
	private String adapterRpcVersion;

	public Properties() {
	}

	public Properties(String wsDebugEnabled, String multipleServersEnabled, String proxyArchitectureEnabled,
			String iaasMonitoringEnabled, String adapterName, String adapterVersion, String adapterRpcVersion) {
		this.wsDebugEnabled = wsDebugEnabled;
		this.multipleServersEnabled = multipleServersEnabled;
		this.proxyArchitectureEnabled = proxyArchitectureEnabled;
		this.iaasMonitoringEnabled = iaasMonitoringEnabled;
		this.adapterName = adapterName;
		this.adapterVersion = adapterVersion;
		this.adapterRpcVersion = adapterRpcVersion;
	}

	public Integer getMonitId() {
		return this.monitId;
	}

	public void setMonitId(Integer monitId) {
		this.monitId = monitId;
	}

	public String getWsDebugEnabled() {
		return this.wsDebugEnabled;
	}

	public void setWsDebugEnabled(String wsDebugEnabled) {
		this.wsDebugEnabled = wsDebugEnabled;
	}

	public String getMultipleServersEnabled() {
		return this.multipleServersEnabled;
	}

	public void setMultipleServersEnabled(String multipleServersEnabled) {
		this.multipleServersEnabled = multipleServersEnabled;
	}

	public String getProxyArchitectureEnabled() {
		return this.proxyArchitectureEnabled;
	}

	public void setProxyArchitectureEnabled(String proxyArchitectureEnabled) {
		this.proxyArchitectureEnabled = proxyArchitectureEnabled;
	}

	public String getIaasMonitoringEnabled() {
		return this.iaasMonitoringEnabled;
	}

	public void setIaasMonitoringEnabled(String iaasMonitoringEnabled) {
		this.iaasMonitoringEnabled = iaasMonitoringEnabled;
	}

	public String getAdapterName() {
		return this.adapterName;
	}

	public void setAdapterName(String adapterName) {
		this.adapterName = adapterName;
	}

	public String getAdapterVersion() {
		return this.adapterVersion;
	}

	public void setAdapterVersion(String adapterVersion) {
		this.adapterVersion = adapterVersion;
	}

	public String getAdapterRpcVersion() {
		return this.adapterRpcVersion;
	}

	public void setAdapterRpcVersion(String adapterRpcVersion) {
		this.adapterRpcVersion = adapterRpcVersion;
	}

}
