package it.reply.monitoring.dao;

/**
 * ServerHasProxy generated by hbm2java
 */
public class ServerHasProxy implements java.io.Serializable {

	private ServerHasProxyId id;

	public ServerHasProxy() {
	}

	public ServerHasProxy(ServerHasProxyId id) {
		this.id = id;
	}

	public ServerHasProxyId getId() {
		return this.id;
	}

	public void setId(ServerHasProxyId id) {
		this.id = id;
	}

}
