package it.reply.monitoring.dao;

/**
 * Server generated by hbm2java
 */
public class Server implements java.io.Serializable {

	private int idServer;
	private String type;
	private String url;
	private String username;
	private String password;
	private String description;

	public Server() {
	}

	public Server(int idServer) {
		this.idServer = idServer;
	}

	public Server(int idServer, String type, String url, String username, String password, String description) {
		this.idServer = idServer;
		this.type = type;
		this.url = url;
		this.username = username;
		this.password = password;
		this.description = description;
	}

	public int getIdServer() {
		return this.idServer;
	}

	public void setIdServer(int idServer) {
		this.idServer = idServer;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
