package it.reply.monitoring.dao;

/**
 * ServerHasProxyId generated by hbm2java
 */
public class ServerHasProxyId implements java.io.Serializable {

	private int proxyId;
	private int serverId;

	public ServerHasProxyId() {
	}

	public ServerHasProxyId(int proxyId, int serverId) {
		this.proxyId = proxyId;
		this.serverId = serverId;
	}

	public int getProxyId() {
		return this.proxyId;
	}

	public void setProxyId(int proxyId) {
		this.proxyId = proxyId;
	}

	public int getServerId() {
		return this.serverId;
	}

	public void setServerId(int serverId) {
		this.serverId = serverId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServerHasProxyId))
			return false;
		ServerHasProxyId castOther = (ServerHasProxyId) other;

		return (this.getProxyId() == castOther.getProxyId()) && (this.getServerId() == castOther.getServerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProxyId();
		result = 37 * result + this.getServerId();
		return result;
	}

}
