package it.reply.monitoring.dao;

/**
 * ZoneHasServerId generated by hbm2java
 */
public class ZoneHasServerId implements java.io.Serializable {

	private int zoneId;
	private int serverId;

	public ZoneHasServerId() {
	}

	public ZoneHasServerId(int zoneId, int serverId) {
		this.zoneId = zoneId;
		this.serverId = serverId;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public int getServerId() {
		return this.serverId;
	}

	public void setServerId(int serverId) {
		this.serverId = serverId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZoneHasServerId))
			return false;
		ZoneHasServerId castOther = (ZoneHasServerId) other;

		return (this.getZoneId() == castOther.getZoneId()) && (this.getServerId() == castOther.getServerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getZoneId();
		result = 37 * result + this.getServerId();
		return result;
	}

}
