package it.reply.monitoring.dao;

/**
 * ZoneHasServer generated by hbm2java
 */
public class ZoneHasServer implements java.io.Serializable {

	private ZoneHasServerId id;

	public ZoneHasServer() {
	}

	public ZoneHasServer(ZoneHasServerId id) {
		this.id = id;
	}

	public ZoneHasServerId getId() {
		return this.id;
	}

	public void setId(ZoneHasServerId id) {
		this.id = id;
	}

}
