package it.reply.monitoring.dao;

/**
 * Zones generated by hbm2java
 */
public class Zones implements java.io.Serializable {

	private int idZones;
	private String zoneName;
	private String distributedArchitecture;

	public Zones() {
	}

	public Zones(int idZones) {
		this.idZones = idZones;
	}

	public Zones(int idZones, String zoneName, String distributedArchitecture) {
		this.idZones = idZones;
		this.zoneName = zoneName;
		this.distributedArchitecture = distributedArchitecture;
	}

	public int getIdZones() {
		return this.idZones;
	}

	public void setIdZones(int idZones) {
		this.idZones = idZones;
	}

	public String getZoneName() {
		return this.zoneName;
	}

	public void setZoneName(String zoneName) {
		this.zoneName = zoneName;
	}

	public String getDistributedArchitecture() {
		return this.distributedArchitecture;
	}

	public void setDistributedArchitecture(String distributedArchitecture) {
		this.distributedArchitecture = distributedArchitecture;
	}

}
